CXX ?= g++
ifneq ($(origin FUNC),undefined)
CXX := $(FUNC)
endif
NATIVE ?= 0
OPENMP ?= 1
EXACT_TRIG ?= 0
REFERENCE_SHADING ?= 0
OPT ?= 3
FAST_MATH ?= 0
CPU_ARCH_FLAGS :=
CPU_THREAD_FLAGS :=
CPU_QUALITY_FLAGS :=
ifeq ($(NATIVE),1)
CPU_ARCH_FLAGS += -march=native
endif
ifeq ($(OPENMP),1)
CPU_THREAD_FLAGS += -fopenmp
endif
ifeq ($(EXACT_TRIG),1)
CPU_QUALITY_FLAGS += -DRAY_EXACT_TRIG
endif
ifeq ($(REFERENCE_SHADING),1)
CPU_QUALITY_FLAGS += -DRAY_REFERENCE_SHADING
endif
ifeq ($(FAST_MATH),1)
CPU_QUALITY_FLAGS += -ffast-math
endif
CPU_FLAGS ?= -O$(OPT) -flto -DNDEBUG -std=c++17 -g -Werror
CPU_COMPILE_FLAGS = $(CPPFLAGS) $(CPU_FLAGS) $(CXXFLAGS) $(CPU_ARCH_FLAGS) $(CPU_THREAD_FLAGS) $(CPU_QUALITY_FLAGS)
CPU_LINK_FLAGS = $(CPU_FLAGS) $(CXXFLAGS) $(CPU_ARCH_FLAGS) $(CPU_THREAD_FLAGS) $(CPU_QUALITY_FLAGS) $(LDFLAGS)
